apiVersion: apps/v1
kind: Deployment
metadata:
  name: resale-dev-sales-front-app
  namespace: dev-resale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resale-dev-sales-front-app
  template:
    metadata:
      labels:
        app: resale-dev-sales-front-app
    spec:
      imagePullSecrets:
        - name: icr-secret
      containers:
        - name: resale-dev-sales-front-app
          image: de.icr.io/dev-registry/loveresale-sales-frontend:latest
          # env:
          #   - name: BANK_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: backend-properties
          #         key: BANK_URL
          #   - name: CHATBOT_ID
          #     valueFrom:
          #       configMapKeyRef:
          #         name: backend-properties
          #         key: CHATBOT_ID
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1000Mi
              cpu: 250m
            requests:
              memory: 200Mi
              cpu: 125m
      dnsPolicy: Default

---
apiVersion: v1
kind: Service
metadata:
  name: resale-dev-sales-front-service-cip
  namespace: dev-resale
  labels:
    app: resale-dev-sales-front-app
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: resale-dev-sales-front-app
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: vso-dev-customer-front-service
#   labels:
#     app: vso-dev-customer-front-service
# spec:
#   type: NodePort
#   ports:
#     # the port that this service should serve on
#     - port: 80
#       targetPort: 8025
#   # label keys and values that must match in order to receive traffic for this service
#   selector:
#     app: vso-dev-customer-front-app

# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: vso-dev-customer-front-ingress
# spec:
#   rules:
#   - host: vso-dev-customer-front-app.cluster-ingress-subdomain
#     http:
#       paths:
#       - backend:
#           serviceName: vso-dev-customer-front-service-cip
#           servicePort: 80
#         path: /
#   tls:
#   - hosts:
#     - vso-dev-customer-front-app.cluster-ingress-subdomain
#     secretName: cluster-ingress-secret
